name: Setup Sccache
inputs:
  parent-key:
    description: Upstream dependency sccache job name, eg. "libmamba_static" for "libmamba_cpp_tests"
    default: n/a
runs:
  using: composite
  steps:
    - name: Generate GitHub cache key
      id: cache-key
      shell: bash -l {0}
      run: |
        key_prefix="sccache-${{ runner.os }}-$(TZ=UTC date +%F)"
        echo ::set-output name=key-prefix::"$key_prefix"
        echo ::set-output name=key::"$key_prefix-${{ github.job }}-$(TZ=UTC date '+%H:%M:%S')"
        echo "SCCACHE_DIR=$HOME/sccache" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
        echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV

    - name: Cache sccache paths
      uses: actions/cache@v2
      with:
        path: ${{ env.SCCACHE_DIR }}
        key: ${{ steps.cache-key.outputs.key }}
        restore-keys: |
          ${{ steps.cache-key.outputs.key-prefix }}-${{ github.job }}
          ${{ steps.cache-key.outputs.key-prefix }}-${{ inputs.parent-key }}

    - name: Sccache stats
      shell: bash -l {0}
      run: |
        sccache --show-stats
        sccache -z
