name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  libmamba_static_win:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016]

    steps:
      - uses: actions/checkout@v2
      - name: setup build
        id: setup
        uses: ./.github/actions/setup
        with:
          environment-file: ./libmamba/environment-dev.yml
      - name: build libmamba-static
        shell: cmd /C call {0}
        run: |
          call micromamba activate build_env
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%\Library ^
                   -DBUILD_LIBMAMBA=ON ^
                   -DBUILD_STATIC=ON ^
                   -GNinja ^
                   -DCMAKE_CXX_COMPILER_LAUNCHER=${{ steps.setup.outputs.ccache_path }} ^
                   -DCMAKE_C_COMPILER_LAUNCHER=${{ steps.setup.outputs.ccache_path }}
          ninja
