name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  libmamba_static:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: create build environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./libmamba/environment-dev.yml
          environment-name: build_env
          cache-env: true
      - uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}
      - name: build libmamba-static
        shell: bash -l {0}
        run: |
          micromamba activate build_env
          mkdir build
          cd build
          cmake .. -DBUILD_LIBMAMBA=ON \
                   -DBUILD_STATIC=ON \
                   -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
                   -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                   -GNinja
          ninja
          sccache --show-stats
          # Do not cache temporary envs with 'cache-env: true'
          rm -rf $(micromamba info --json | jq -r '."env location"')/envs

  umamba_tests:
    needs: [libmamba_static]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: create build environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./micromamba/environment-dev.yml
          environment-name: build_env
          cache-env: true
      - uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}
          restore-keys: |
            libmamba_static-${{ matrix.os }}
      - name: build micromamba
        shell: bash -l {0}
        run: |
          micromamba activate build_env
          mkdir build
          cd build
          cmake .. -DBUILD_MICROMAMBA=ON \
                   -DBUILD_LIBMAMBA=ON \
                   -DBUILD_SHARED=ON \
                   -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
                   -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                   -GNinja
          ninja
          sccache --show-stats
          micromamba/micromamba --log-level trace info
          micromamba/micromamba --log-level trace info | grep -q debug
