name: Test micro.mamba.pm

on:
  push: null
  pull_request: null
  schedule:
    - cron: '0 10 * * *'

permissions:
  contents: read
  issues: write

jobs:
  test_micro_mamba_pm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - shell: bash
        run: |
          set -eux
          function platform_name {
            uname="$(echo "$(uname -a)" | tr "[:upper:]" "[:lower:]")"
            if [[ "$uname" =~ darwin.+arm64 ]]; then echo osx-arm64
            elif [[ "$uname" =~ darwin.+x86_64 ]]; then echo osx-64
            elif [[ "$uname" =~ linux.+arm64 ]]; then echo linux-aarch64
            elif [[ "$uname" =~ linux.+x86_64 ]]; then echo linux-64
            elif [[ "$uname" =~ win ]] || [[ "$uname" =~ mingw ]]; then echo win-64
            fi
          }
          function binary_name {
            if [[ $(platform_name) =~ win ]]; then
              echo Library/bin/micromamba.exe
            else
              echo bin/micromamba
            fi
          }
          curl -Ls https://micro.mamba.pm/api/micromamba/$(platform_name)/latest | bunzip2 | tar xOf - $(binary_name) > m
          chmod +x m
          ./m info
      - uses: dblock/create-a-github-issue@2c9fa0d32c24d651281c37d21e5b49e333500fe8
        if: failure()
        with:
          filename: .github/workflows/test_issue.md
          update_existing: true
          search_existing: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
