name: Test micro.mamba.pm

on:
  push: null
  pull_request: null
  schedule:
    - cron: '0 10 * * *'

jobs:
  test_micro_mamba_pm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - shell: bash
        run: |
          set -eux
          function platform_name () {
            uname="$(echo "$(uname -a)" | tr "[:upper:]" "[:lower:]")"
            if [[ "$uname" =~ darwin.+arm64 ]]; then echo osx-arm64
            elif [[ "$uname" =~ linux.+arm64 ]]; then echo linux-aarch64
            elif [[ "$uname" =~ linux.+x86_64 ]]; then echo linux-64
            elif [[ "$uname" =~ win ]] && [[ "$uname" =~ mingw ]]; then echo win-64
            fi
          }
          curl -Ls https://micro.mamba.pm/api/micromamba/$(platform_name)/latest | tar -xvj bin/micromamba
          bin/micromamba info
